server:
  host: "0.0.0.0"
  port: 8080

mysql:
  dbuser:     "root"
  dbpassword: "password"
  dbname:     "mySql"
  dbhost:     "0.0.0.0"
  dbport:     3306

redis:
  host: "redis"
  port: 6379
  password: ""
  db: 0